.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2019 Philip J. Freeman <elektron@halo.nu>,
.\"
.TH LIST_PRODUCT_INFORMATION 1 "February  2 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
list-product-information \- List products on the n2k network
.SH SYNOPSIS
.B list-product-information
.SH DESCRIPTION
This manual page documents briefly the
.B list-product-information
command.
.PP
.B list-product-information
is a program that shows which devices are present on the NMEA 2000 bus,
and what software versions they are running.
.SH OPTIONS
None
.SH SEE ALSO
.BR n2kd_monitor (1).
.br
The program is documented fully by the GitHub project Wiki, here:
https://github.com/canboat/canboat/wiki/List-product-information
